config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get "home/about" => "homes#about"
  devise_for :users


  resources :users, only: [:show, :edit, :update, :index] do
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :relationships, only: [:create, :destroy, ]
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
  	belongs_to :book

  	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
 	belongs_to :book

 	validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後に遷移するpathを設定
    end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book_find = Book.find(params[:book_id])
	    comment = current_user.book_comments.new(book_comment_params)
	    comment.book_id = book_find.id
	    if comment.save
	      flash[:success] = "Comment was successfully created."
	    end
	    redirect_to book_path(book_find)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    	redirect_to book_path(params[:book_id])
	end

	private

  	def book_comment_params
    	params.require(:book_comment).permit(:comment)
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_find = Book.find(params[:id])
    @book = Book.new
    @user = @book_find.user
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: 'You have creatad book successfully.'
    else
      @books = Book.all
      @user = @book.user
      render :index
    end
  end

  def edit
  end

  def update
    @book_find = Book.find(params[:id])
    if @book_find.update(book_params)
      redirect_to @books, notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book_find = Book.find(params[:id])
    @book_find.destroy
    redirect_to @book_find
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book_find = Book.find(params[:id])
    @user = @book_find.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
  	book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
    end
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
    end
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end

  def show
    @user_find = User.find(params[:id])
    @books = @user_find.books
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: 'You have creatad book successfully.'
    else
      @books = Book.all
      @users = User.all
      @user = current_user
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite.html.erb
<% if book_find.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book_find), method: :delete do %>
    <i class="fas fa-heart" aria-hidden="true" ></i>
    <%= book_find.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book_find), method: :post do %>
    <i class="far fa-heart" aria-hidden="true"></i>
    <%= book_find.favorites.count %>
  <% end %>
<% end %>

app/views/books/_list.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg",size:'100x100' %>
    <table class="table">
      <thead>
        <tr>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count, followings_user_path(user.id)%></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <% if current_user == @user %>
          <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
      <% else %>
          <%= render 'relationships/follow_button', user: user %>
      <% end %>
    </div>

    <h2>New book</h2>
    <%= form_for(book, url:"/books#{book.id}") do |f| %>
       <div class="field row">
          <label for="book_title">Title</label>
          <div><%= f.text_field :title, class: "book_title col-xs-12" %></div>
       </div>
       <div class="field row">
          <label for="book_body">Opinion</label>
          <div><%= f.text_area :body, class: "book_body col-xs-12"%></div>
       </div>
      <div class="actions row">
        <div><%= f.submit 'Create Book',class: " col-xs-12" %></div>
      </div>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
		<%= form_for(@book_find) do |f| %>
			<% if @book_find.errors.any? %>
			  <div id="error_explanation">
			    <h3><%= pluralize(@book_find.errors.count, "error") %> prohibited this book from being saved:</h3>
			    <ul>
			      <% @book_find.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
				<div class="field row">
					<div class="field_with_errors">
						<label for="book_title">Title</label>
					</div>
					<div class="field_with_errors">
					<%= f.text_field :title, class: "col-xs-12" %>
					</div>
			  </div>
				<div class="field row">
					<div class="field_with_errors">
						<label for="book_body">Opinion</label>
					</div>
					<div class="field_with_errors">
					<%= f.text_area :body, class: "col-xs-12" %>
					</div>
				</div>
			<% else %>
				<div class="field row">
						<label for="book_title">Title</label>
						<div><%= f.text_field :title, class: "book_title col-xs-12" %></div>
				</div>
				<div class="field row">
						<label for="book_body">Opinion</label>
						<div><%= f.text_area :body, class: "book_body col-xs-12"%></div>
				</div>
			<% end %>
				<div class='actions row'>
					<%= f.submit 'Update Book',class: "btn btn-primary col-xs-12" %>
				</div>
		<% end %>
		<%= link_to "Show", book_path(@book_find) %>
		|
		<a class="back" href="/books">Back</a>
	</div>
</div>

app/views/books/index.html.erb
<div class="row">

<%= render 'books/list', book:@book, user:@user %>

  <div class="col-xs-9">
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= render 'books/favorite', book_find: book %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">

<% if @book_comment.errors.any? %>
        <div id="error_explanation">
          <h2> prohibited this comment from being saved:</h2>
          <ul>
            <% @book_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

<%= render 'books/list', book:@book , user:@user %>

  <div class="col-xs-9">
    <h2>Book detail</h2>


    <table class="table table-hover table-inverse">
      <thead>
        <tr>
        </tr>
      </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",size:'40x40' %><br>
              <%= @user.name %>
              <% end %>
         		</td>
            <td><%= link_to @book_find.title, book_path(@book_find.id) %></td>
            <td><%= @book_find.body %></td>
              <% if current_user == @user %>
                <td><%= link_to "Edit", edit_book_path(@book_find.id), class:"btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book_find), method: :delete, "data-confirm" => "本当に削除しますか?", class:"btn-sm btn-danger" %></td>
              <% end %>
            <td>
            <!-- いいね機能 -->
            <%= render 'books/favorite', book_find: @book_find %>
            </td>
            <td>
              コメント数: <%= @book_find.book_comments.count %>
            </td>
          </tr>
        </tbody>
    </table>

    <!-- コメント一覧 -->
     <% @book_find.book_comments.each do |book_comment| %>
      <div class="comment_flex">
        <div><%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg",size:'48x48' %></div>
        <div><%= book_comment.comment %></div>
        <div><% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, "data-confirm" => "本当に削除しますか?", class:"btn-sm btn-danger" %>
        <% end %></div>
      </div>
      <%= book_comment.user.name %>
     <% end %>

    <!-- コメントform -->
    <%= form_for [@book_find, @book_comment] do |f| %>
      <div class="comment_flex">
          <%= f.text_area :comment, class: "col-xs-10" %>
          <%= f.submit '送信'%>
      </div>
    <% end %>

  </div>
</div>

app/views/homes/about.html.erb
<div class="row">
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>

app/views/homes/index.html.erb
<div class="row">
<div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <nav class="navbar-header navbar-left">
          <span class="white">Bookers</span>
        </nav>
        
        <div>
          <ul class="nav navbar-nav navbar-right flex-column flex-sm-row">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to ' Home', user_path(current_user), class: "glyphicon glyphicon-home home " %>
              </li>
              <li class="nav-item">
                <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users" %>
              </li>
              <li class="nav-item">
                <%= link_to ' Books', books_path, class: "glyphicon glyphicon-book books" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home home flex-sm-fill text-sm-center" %>
              </li>
              <li class="nav-item">
                <%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link about flex-sm-fill text-sm-center" %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up flex-sm-fill text-sm-center" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in flex-sm-fill text-sm-center" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      </nav>
    </header>

    <div class="body">
      <div class="container">

        <p id="notice">
          <%= notice %>
        </p>
            <%= yield %>
      </div>
    </div>

    <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
    </footer>
    </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/_follow_tablebutton.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローを外す', class: 'btn btn-link' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn btn-link' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <div class="field">
          <div class="field_with_errors">
            <label>Name</label>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="field">
            <label>Image</label>
            <%= f.attachment_field :profile_image %>
        </div>
        <div class="field">
          <div class="filed_with_errors">
            <label>Intoroduction</label>
            <%= f.text_area :introduction %>
          </div>
        </div>
      <% else %>
       <div class="field">
          <label for="book_title">Name</label>
          <div><%= f.text_field :name %></div>
       </div>
       <div class="field">
          <div class="field_with_errors">
            <label>Image</label>
            <%= f.attachment_field :profile_image %>
          </div>
        </div>
       <div class="field">
          <label>Introduction</label>
          <div><%= f.text_area :introduction %></div>
       </div>
      <% end %>
      <div class="actions">
        <%= f.submit 'Update User' %>
      </div>
    <% end %>

app/views/users/followers.html.erb
<div class="row">

    <h2>Follower Users</h2>

    <% if @user.followers.present? %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg",size:'40x40' %></td>
              <td><%= user.name %></td>
              <td>フォロー数:<%= user.followings.count %></td>
              <td>フォロワー数:<%= user.followers.count %></td>
              <td><%= render 'relationships/follow_tablebutton', user:user %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <p>ユーザがいません。</p>
    <% end %>

</div>

app/views/users/followings.html.erb
<div class="row">

    <h2>Follow Users</h2>

    <% if @user.followings.present? %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg",size:'40x40' %></td>
              <td><%= user.name %></td>
              <td>フォロー数:<%= user.followings.count %></td>
              <td>フォロワー数:<%= user.followers.count %></td>
              <td><%= render 'relationships/follow_tablebutton', user:user %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <p>ユーザがいません。</p>
    <% end %>

</div>

app/views/users/index.html.erb
<div class="row">

  <%= render 'books/list', books:@books, book:@book, user:@user %>

  <div class="col-xs-9">
    <h2>Users</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg",size:'40x40' %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= render 'relationships/follow_tablebutton', user:user %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <%= render 'books/list', books:@books, book:@book, user:@user_find %>
  <div class="col-xs-9">

    <h2>Books</h2>
    <table class="table table-inverse">
      <thead>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag @user_find, :profile_image, fallback: "no_image.jpg",size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>